name: GraalVM Native Image build
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [latest, dev, '22.0.0.2']
        jdk: [11, 17]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: ${{ matrix.jdk }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Test.java on Windows
        run: |
          javac.exe Test.java
          native-image.cmd Test
        if: runner.os == 'Windows'

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jdk }}
          path: test*

      - name: Run Test.java on Windows
        run: |
          java Test
        if: runner.os == 'Windows'

      - name: Run test on Windows
        run: |
          ./test.exe
        if: runner.os == 'Windows'
